from datetime import datetime
from typing import Any, Generic, Type, TypeVar

from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.orm import Session


ModelType = TypeVar("ModelType")
CreateSchemaType = TypeVar("CreateSchemaType", bound=BaseModel)
UpdateSchemaType = TypeVar("UpdateSchemaType", bound=BaseModel)


class CRUDBase(
    Generic[ModelType, CreateSchemaType, UpdateSchemaType]
):
    def __init__(self, model: Type[ModelType]):
        self.model = model

    def get(
        self,
        db: Session,
        id: Any,
    ) -> ModelType | None:
        return db.get(self.model, id)

    def get_multi(
        self,
        db: Session,
        *,
        skip: int = 0,
        limit: int = 100,
    ) -> list[ModelType]:
        statement = (
            select(self.model)
            .offset(skip)
            .limit(limit)
        )

        return list(db.scalars(statement).all())

    def create(
        self,
        db: Session,
        obj_in: CreateSchemaType,
    ) -> ModelType:

        # Only use fields actually supplied by the request.
        if hasattr(obj_in, "model_dump"):
            data = obj_in.model_dump(exclude_unset=True)
        else:
            data = obj_in.dict(exclude_unset=True)

        # created_at and updated_at are generated by the backend.
        # Never send None into NOT NULL timestamp columns.
        now = datetime.utcnow()

        if "created_at" in data and data["created_at"] is None:
            data.pop("created_at")

        if "updated_at" in data and data["updated_at"] is None:
            data.pop("updated_at")

        # If the model has these columns, provide timestamps explicitly.
        model_columns = getattr(self.model, "__table__", None)

        if model_columns is not None:
            column_names = {
                column.name
                for column in model_columns.columns
            }

            if "created_at" in column_names:
                data["created_at"] = now

            if "updated_at" in column_names:
                data["updated_at"] = now

        db_obj = self.model(**data)

        db.add(db_obj)

        try:
            db.commit()
            db.refresh(db_obj)
        except Exception:
            db.rollback()
            raise

        return db_obj

    def update(
        self,
        db: Session,
        db_obj: ModelType,
        obj_in: UpdateSchemaType | dict[str, Any],
    ) -> ModelType:

        if isinstance(obj_in, dict):
            update_data = obj_in
        elif hasattr(obj_in, "model_dump"):
            update_data = obj_in.model_dump(exclude_unset=True)
        else:
            update_data = obj_in.dict(exclude_unset=True)

        # Never overwrite timestamps with None.
        update_data.pop("created_at", None)

        if "updated_at" in update_data:
            update_data.pop("updated_at")

        for field, value in update_data.items():
            setattr(db_obj, field, value)

        # Automatically update modification timestamp.
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()

        db.add(db_obj)

        try:
            db.commit()
            db.refresh(db_obj)
        except Exception:
            db.rollback()
            raise

        return db_obj

    def remove(
        self,
        db: Session,
        id: Any,
    ) -> ModelType | None:

        db_obj = self.get(db, id)

        if db_obj is None:
            return None

        db.delete(db_obj)

        try:
            db.commit()
        except Exception:
            db.rollback()
            raise

        return db_obj