"""initial_schema

Revision ID: 97b03d9a5a49
Revises: 
Create Date: 2026-08-08 11:23:09.181582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97b03d9a5a49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'course_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.alter_column('course', 'program_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('course', 'semester_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('course', 'is_lab',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='academic')
    op.alter_column('course', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('course', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.drop_constraint(op.f('uq_course_code'), 'course', schema='academic', type_='unique')
    op.create_foreign_key(None, 'course', 'program', ['program_id'], ['program_id'], source_schema='academic', referent_schema='academic')
    op.alter_column('department', 'department_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.alter_column('department', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('department', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('enrollment', 'enrollment_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.alter_column('enrollment', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('enrollment', 'section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('enrollment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='academic')
    op.alter_column('enrollment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='academic')
    op.drop_index(op.f('idx_enrollment_section'), table_name='enrollment', schema='academic')
    op.drop_index(op.f('idx_enrollment_student'), table_name='enrollment', schema='academic')
    op.alter_column('program', 'program_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.alter_column('program', 'department_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('program', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('program', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('section', 'section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.alter_column('section', 'course_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('section', 'teacher_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('section', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('section', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.drop_constraint(op.f('chk_max_students'), 'section', schema='academic', type_='check')
    op.alter_column('semester', 'semester_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.alter_column('semester', 'program_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('semester', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='academic')
    op.alter_column('semester', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('semester', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('student', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.alter_column('student', 'program_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('student', 'semester_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('student', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='academic')
    op.alter_column('student', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='academic')
    op.alter_column('student', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='academic')
    op.drop_index(op.f('idx_student_program'), table_name='student', schema='academic')
    op.drop_index(op.f('idx_student_semester'), table_name='student', schema='academic')
    op.create_foreign_key(None, 'student', 'program', ['program_id'], ['program_id'], source_schema='academic', referent_schema='academic')
    op.create_foreign_key(None, 'student', 'semester', ['semester_id'], ['semester_id'], source_schema='academic', referent_schema='academic')
    op.alter_column('teacher', 'teacher_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.alter_column('teacher', 'department_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('teacher', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='academic')
    op.alter_column('teacher', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('teacher', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='academic')
    op.create_foreign_key(None, 'teacher', 'department', ['department_id'], ['department_id'], source_schema='academic', referent_schema='academic')
    op.alter_column('face_embedding', 'embedding_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.alter_column('face_embedding', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_embedding', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_embedding', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_embedding', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.drop_index(op.f('idx_face_embedding_student'), table_name='face_embedding', schema='ai')
    op.alter_column('face_registration', 'registration_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.alter_column('face_registration', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_registration', 'total_images',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_registration', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_registration', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.add_column('face_verification_log', sa.Column('captured_image', sa.Text(), nullable=True), schema='ai')
    op.alter_column('face_verification_log', 'verification_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.alter_column('face_verification_log', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_verification_log', 'session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_verification_log', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_verification_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_verification_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.create_foreign_key(None, 'face_verification_log', 'recognition_session', ['session_id'], ['recognition_session_id'], source_schema='ai', referent_schema='ai')
    op.drop_column('face_verification_log', 'captured_image_path', schema='ai')
    op.add_column('recognition_result', sa.Column('processing_time', sa.Integer(), nullable=False), schema='ai')
    op.alter_column('recognition_result', 'result_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.alter_column('recognition_result', 'recognition_session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_result', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_result', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_result', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.drop_index(op.f('idx_recognition_result_session'), table_name='recognition_result', schema='ai')
    op.drop_index(op.f('idx_recognition_result_student'), table_name='recognition_result', schema='ai')
    op.drop_constraint(op.f('chk_confidence_score'), 'recognition_result', schema='ai', type_='check')
    op.drop_column('recognition_result', 'processing_time_ms', schema='ai')
    op.alter_column('recognition_session', 'recognition_session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.alter_column('recognition_session', 'attendance_session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_session', 'total_faces_detected',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False,
               schema='ai')
    op.alter_column('recognition_session', 'total_faces_recognized',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False,
               schema='ai')
    op.alter_column('recognition_session', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_session', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='ai')
    op.alter_column('recognition_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_session', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False,
               schema='ai')
    op.alter_column('attendance', 'attendance_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='attendance')
    op.alter_column('attendance', 'attendance_session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='attendance')
    op.drop_index(op.f('idx_attendance_session'), table_name='attendance', schema='attendance')
    op.drop_index(op.f('idx_attendance_student'), table_name='attendance', schema='attendance')
    op.add_column('attendance_adjustment', sa.Column('attendance_adjustment_id', sa.Integer(), nullable=False), schema='attendance')
    op.add_column('attendance_adjustment', sa.Column('adjusted_by', sa.String(length=100), nullable=False), schema='attendance')
    op.add_column('attendance_adjustment', sa.Column('adjusted_at', sa.DateTime(), nullable=False), schema='attendance')
    op.alter_column('attendance_adjustment', 'attendance_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_adjustment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_adjustment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='attendance')
    op.drop_constraint(op.f('fk_adjustment_teacher'), 'attendance_adjustment', schema='attendance', type_='foreignkey')
    op.drop_column('attendance_adjustment', 'adjusted_by_teacher_id', schema='attendance')
    op.drop_column('attendance_adjustment', 'adjustment_time', schema='attendance')
    op.drop_column('attendance_adjustment', 'adjustment_id', schema='attendance')
    op.alter_column('attendance_audit_log', 'audit_log_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='attendance')
    op.alter_column('attendance_audit_log', 'attendance_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_audit_log', 'performed_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_audit_log', 'action_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_session', 'attendance_session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='attendance')
    op.alter_column('attendance_session', 'section_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_session', 'teacher_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_session', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='attendance')
    op.add_column('attendance_summary', sa.Column('attendance_summary_id', sa.Integer(), nullable=False), schema='attendance')
    op.add_column('attendance_summary', sa.Column('attendance_session_id', sa.Integer(), nullable=False), schema='attendance')
    op.add_column('attendance_summary', sa.Column('total_students', sa.Integer(), nullable=False), schema='attendance')
    op.add_column('attendance_summary', sa.Column('present_students', sa.Integer(), nullable=False), schema='attendance')
    op.add_column('attendance_summary', sa.Column('absent_students', sa.Integer(), nullable=False), schema='attendance')
    op.add_column('attendance_summary', sa.Column('late_students', sa.Integer(), nullable=False), schema='attendance')
    op.add_column('attendance_summary', sa.Column('summary_date', sa.Date(), nullable=False), schema='attendance')
    op.alter_column('attendance_summary', 'attendance_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               type_=sa.Integer(),
               nullable=False,
               schema='attendance')
    op.alter_column('attendance_summary', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_summary', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='attendance')
    op.drop_constraint(op.f('fk_attendance_summary_semester'), 'attendance_summary', schema='attendance', type_='foreignkey')
    op.drop_constraint(op.f('fk_attendance_summary_student'), 'attendance_summary', schema='attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_summary', 'attendance_session', ['attendance_session_id'], ['attendance_session_id'], source_schema='attendance', referent_schema='attendance')
    op.drop_constraint(op.f('chk_attendance_percentage'), 'attendance_summary', schema='attendance', type_='check')
    op.drop_column('attendance_summary', 'late_classes', schema='attendance')
    op.drop_column('attendance_summary', 'summary_id', schema='attendance')
    op.drop_column('attendance_summary', 'absent_classes', schema='attendance')
    op.drop_column('attendance_summary', 'attended_classes', schema='attendance')
    op.drop_column('attendance_summary', 'total_classes', schema='attendance')
    op.drop_column('attendance_summary', 'semester_id', schema='attendance')
    op.drop_column('attendance_summary', 'student_id', schema='attendance')
    op.alter_column('login_audit', 'login_audit_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.alter_column('login_audit', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('login_audit', 'login_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.alter_column('login_audit', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.alter_column('login_audit', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.drop_index(op.f('idx_login_audit_user'), table_name='login_audit', schema='auth')
    op.add_column('permission', sa.Column('permission_description', sa.String(length=255), nullable=True), schema='auth')
    op.alter_column('permission', 'permission_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.alter_column('permission', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.alter_column('permission', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.drop_column('permission', 'permission_code', schema='auth')
    op.drop_column('permission', 'description', schema='auth')
    op.alter_column('role', 'role_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.alter_column('role', 'role_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False,
               schema='auth')
    op.alter_column('role', 'role_description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='auth')
    op.alter_column('role', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.alter_column('role', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.alter_column('role_permission', 'role_permission_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.alter_column('role_permission', 'role_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('role_permission', 'permission_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('role_permission', 'granted_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.alter_column('role_permission', 'granted_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='auth')
    op.alter_column('role_permission', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.alter_column('role_permission', 'created_by',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.drop_constraint(op.f('fk_role_permission_granted_by'), 'role_permission', schema='auth', type_='foreignkey')
    op.alter_column('user_account', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.alter_column('user_account', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_account', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_account', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.drop_constraint(op.f('uq_user_email'), 'user_account', schema='auth', type_='unique')
    op.drop_constraint(op.f('uq_username'), 'user_account', schema='auth', type_='unique')
    op.alter_column('user_role', 'user_role_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.alter_column('user_role', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_role', 'role_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_role', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_role', 'assigned_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='auth')
    op.alter_column('user_role', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_role', 'created_by',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False,
               schema='auth')
    op.drop_index(op.f('idx_user_role_user'), table_name='user_role', schema='auth')
    op.drop_constraint(op.f('fk_user_role_assigned_by'), 'user_role', schema='auth', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_user_role_assigned_by'), 'user_role', 'user_account', ['assigned_by'], ['user_id'], source_schema='auth', referent_schema='auth')
    op.create_index(op.f('idx_user_role_user'), 'user_role', ['user_id'], unique=False, schema='auth')
    op.alter_column('user_role', 'created_by',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_role', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_role', 'assigned_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='auth')
    op.alter_column('user_role', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_role', 'role_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_role', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_role', 'user_role_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.create_unique_constraint(op.f('uq_username'), 'user_account', ['username'], schema='auth', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_user_email'), 'user_account', ['email'], schema='auth', postgresql_nulls_not_distinct=False)
    op.alter_column('user_account', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_account', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_account', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('user_account', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.create_foreign_key(op.f('fk_role_permission_granted_by'), 'role_permission', 'user_account', ['granted_by'], ['user_id'], source_schema='auth', referent_schema='auth')
    op.alter_column('role_permission', 'created_by',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('role_permission', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('role_permission', 'granted_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               schema='auth')
    op.alter_column('role_permission', 'granted_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('role_permission', 'permission_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('role_permission', 'role_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('role_permission', 'role_permission_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.alter_column('role', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('role', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('role', 'role_description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='auth')
    op.alter_column('role', 'role_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='auth')
    op.alter_column('role', 'role_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.add_column('permission', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True), schema='auth')
    op.add_column('permission', sa.Column('permission_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='auth')
    op.alter_column('permission', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('permission', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('permission', 'permission_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.drop_column('permission', 'permission_description', schema='auth')
    op.create_index(op.f('idx_login_audit_user'), 'login_audit', ['user_id'], unique=False, schema='auth')
    op.alter_column('login_audit', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('login_audit', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('login_audit', 'login_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='auth')
    op.alter_column('login_audit', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('login_audit', 'login_audit_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='auth')
    op.add_column('attendance_summary', sa.Column('student_id', sa.BIGINT(), autoincrement=False, nullable=False), schema='attendance')
    op.add_column('attendance_summary', sa.Column('semester_id', sa.BIGINT(), autoincrement=False, nullable=False), schema='attendance')
    op.add_column('attendance_summary', sa.Column('total_classes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True), schema='attendance')
    op.add_column('attendance_summary', sa.Column('attended_classes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True), schema='attendance')
    op.add_column('attendance_summary', sa.Column('absent_classes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True), schema='attendance')
    op.add_column('attendance_summary', sa.Column('summary_id', sa.BIGINT(), autoincrement=False, nullable=False), schema='attendance')
    op.add_column('attendance_summary', sa.Column('late_classes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True), schema='attendance')
    op.create_check_constraint(op.f('chk_attendance_percentage'), 'attendance_summary', 'attendance_percentage >= 0::numeric AND attendance_percentage <= 100::numeric', schema='attendance')
    op.drop_constraint(None, 'attendance_summary', schema='attendance', type_='foreignkey')
    op.create_foreign_key(op.f('fk_attendance_summary_student'), 'attendance_summary', 'student', ['student_id'], ['student_id'], source_schema='attendance', referent_schema='academic')
    op.create_foreign_key(op.f('fk_attendance_summary_semester'), 'attendance_summary', 'semester', ['semester_id'], ['semester_id'], source_schema='attendance', referent_schema='academic')
    op.alter_column('attendance_summary', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_summary', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_summary', 'attendance_percentage',
               existing_type=sa.Integer(),
               server_default=sa.text('0'),
               type_=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               schema='attendance')
    op.drop_column('attendance_summary', 'summary_date', schema='attendance')
    op.drop_column('attendance_summary', 'late_students', schema='attendance')
    op.drop_column('attendance_summary', 'absent_students', schema='attendance')
    op.drop_column('attendance_summary', 'present_students', schema='attendance')
    op.drop_column('attendance_summary', 'total_students', schema='attendance')
    op.drop_column('attendance_summary', 'attendance_session_id', schema='attendance')
    op.drop_column('attendance_summary', 'attendance_summary_id', schema='attendance')
    op.alter_column('attendance_session', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_session', 'teacher_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_session', 'section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_session', 'attendance_session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='attendance')
    op.alter_column('attendance_audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_audit_log', 'action_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_audit_log', 'performed_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_audit_log', 'attendance_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_audit_log', 'audit_log_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='attendance')
    op.add_column('attendance_adjustment', sa.Column('adjustment_id', sa.BIGINT(), autoincrement=False, nullable=False), schema='attendance')
    op.add_column('attendance_adjustment', sa.Column('adjustment_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False), schema='attendance')
    op.add_column('attendance_adjustment', sa.Column('adjusted_by_teacher_id', sa.BIGINT(), autoincrement=False, nullable=False), schema='attendance')
    op.create_foreign_key(op.f('fk_adjustment_teacher'), 'attendance_adjustment', 'teacher', ['adjusted_by_teacher_id'], ['teacher_id'], source_schema='attendance', referent_schema='academic')
    op.alter_column('attendance_adjustment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_adjustment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance_adjustment', 'attendance_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='attendance')
    op.drop_column('attendance_adjustment', 'adjusted_at', schema='attendance')
    op.drop_column('attendance_adjustment', 'adjusted_by', schema='attendance')
    op.drop_column('attendance_adjustment', 'attendance_adjustment_id', schema='attendance')
    op.create_index(op.f('idx_attendance_student'), 'attendance', ['student_id'], unique=False, schema='attendance')
    op.create_index(op.f('idx_attendance_session'), 'attendance', ['attendance_session_id'], unique=False, schema='attendance')
    op.alter_column('attendance', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance', 'attendance_session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='attendance')
    op.alter_column('attendance', 'attendance_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='attendance')
    op.alter_column('recognition_session', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True,
               schema='ai')
    op.alter_column('recognition_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_session', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='ai')
    op.alter_column('recognition_session', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_session', 'total_faces_recognized',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True,
               schema='ai')
    op.alter_column('recognition_session', 'total_faces_detected',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True,
               schema='ai')
    op.alter_column('recognition_session', 'attendance_session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_session', 'recognition_session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.add_column('recognition_result', sa.Column('processing_time_ms', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True), schema='ai')
    op.create_check_constraint(op.f('chk_confidence_score'), 'recognition_result', 'confidence_score >= 0::numeric AND confidence_score <= 100::numeric', schema='ai')
    op.create_index(op.f('idx_recognition_result_student'), 'recognition_result', ['student_id'], unique=False, schema='ai')
    op.create_index(op.f('idx_recognition_result_session'), 'recognition_result', ['recognition_session_id'], unique=False, schema='ai')
    op.alter_column('recognition_result', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_result', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_result', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_result', 'recognition_session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('recognition_result', 'result_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.drop_column('recognition_result', 'processing_time', schema='ai')
    op.add_column('face_verification_log', sa.Column('captured_image_path', sa.TEXT(), autoincrement=False, nullable=True), schema='ai')
    op.drop_constraint(None, 'face_verification_log', schema='ai', type_='foreignkey')
    op.alter_column('face_verification_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_verification_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_verification_log', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_verification_log', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_verification_log', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_verification_log', 'verification_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.drop_column('face_verification_log', 'captured_image', schema='ai')
    op.alter_column('face_registration', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_registration', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_registration', 'total_images',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_registration', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_registration', 'registration_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.create_index(op.f('idx_face_embedding_student'), 'face_embedding', ['student_id'], unique=False, schema='ai')
    op.alter_column('face_embedding', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_embedding', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_embedding', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_embedding', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='ai')
    op.alter_column('face_embedding', 'embedding_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='ai')
    op.drop_constraint(None, 'teacher', schema='academic', type_='foreignkey')
    op.alter_column('teacher', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('teacher', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('teacher', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False,
               schema='academic')
    op.alter_column('teacher', 'department_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('teacher', 'teacher_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.drop_constraint(None, 'student', schema='academic', type_='foreignkey')
    op.drop_constraint(None, 'student', schema='academic', type_='foreignkey')
    op.create_index(op.f('idx_student_semester'), 'student', ['semester_id'], unique=False, schema='academic')
    op.create_index(op.f('idx_student_program'), 'student', ['program_id'], unique=False, schema='academic')
    op.alter_column('student', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='academic')
    op.alter_column('student', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='academic')
    op.alter_column('student', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False,
               schema='academic')
    op.alter_column('student', 'semester_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('student', 'program_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('student', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.alter_column('semester', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('semester', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('semester', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False,
               schema='academic')
    op.alter_column('semester', 'program_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('semester', 'semester_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.create_check_constraint(op.f('chk_max_students'), 'section', 'max_students > 0', schema='academic')
    op.alter_column('section', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('section', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('section', 'teacher_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('section', 'course_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('section', 'section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.alter_column('program', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('program', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('program', 'department_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('program', 'program_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.create_index(op.f('idx_enrollment_student'), 'enrollment', ['student_id'], unique=False, schema='academic')
    op.create_index(op.f('idx_enrollment_section'), 'enrollment', ['section_id'], unique=False, schema='academic')
    op.alter_column('enrollment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='academic')
    op.alter_column('enrollment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False,
               schema='academic')
    op.alter_column('enrollment', 'section_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('enrollment', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('enrollment', 'enrollment_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.alter_column('department', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('department', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('department', 'department_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    op.drop_constraint(None, 'course', schema='academic', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_course_code'), 'course', ['course_code'], schema='academic', postgresql_nulls_not_distinct=False)
    op.alter_column('course', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('course', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               schema='academic')
    op.alter_column('course', 'is_lab',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False,
               schema='academic')
    op.alter_column('course', 'semester_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('course', 'program_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='academic')
    op.alter_column('course', 'course_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='academic')
    # ### end Alembic commands ###
